[project]
name = "travel-planner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "langchain", "dotenv", "langchain-community", "pydantic", "fastapi", "langchain-groq", "langchain-mistralai", "uvicorn"
]
